name: lint and format gorabbit

on:
  push:
    branches:
      - "**"

jobs:
  releases-matrix:
    name: Release barat
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2

      - name:
        run: which golangci-lint || (go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.2)

      - name:
        run: golangci-lint run --exclude-use-default=false --disable-all --enable=revive -c .golangci-lint.yml ./pkg/...
